name: Python Application

on:
  schedule:
    # Chạy tự động theo lịch, ví dụ: mỗi 6 giờ
    - cron: "0 */6 * * *"

  # Tùy chọn: Chạy khi có thay đổi trên nhánh `main`
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Chọn phiên bản Python, ví dụ: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Nếu bạn có tệp requirements.txt

    - name: Run Python script
      run: python claimbit.py  # Thay "script.py" bằng tên tệp Python của bạn
